[package]
name = "zim"
version = "0.1.0"
edition = "2024"

[dependencies]
termion = "4"
anyhow = "1.0"
thiserror = "2.0"
arboard = "3.6.1"
unicode-segmentation = "1.11"
unicode-width = "0.1"

[dev-dependencies]
tempfile = "3.10"

